version: '3.8'
services:
  web:
    build:
      context: ./
      target: deps
    volumes:
      - .:/app
    command: sh -c "npm run dev"
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
